from trainers.trainer import Trainer
from trainers.regression_trainer import AccidentRegressionTrainer
from trainers.traffic_volume_trainer import VolumeRegressionTrainer
from trainers.multitask_trainer import MultitaskTrainer
from trainers.supcon_trainer import SupConTrainer
from trainers.sam_trainer import SAMTrainer